name: partomat_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '^3.7.0' # Add SDK constraint

dependencies:
  flutter:
    sdk: flutter
  # ... existing code ...

  # Add the following lines
  firebase_core: ^3.1.1 
  firebase_auth: ^5.1.1
  firebase_app_check: ^0.3.0+1
  google_sign_in: ^6.3.0
  # ... existing code ... 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/google_logo.png # Assuming you have this asset 